version: 2

project_name: fifi

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: fifi
    main: ./cmd/fifi/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildDate={{.Date}}
    # Generate binaries with platform-specific names for direct download
    binary: >-
      fifi_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if eq .Os "windows" }}.exe{{ end }}

archives:
  - id: fifi
    format_overrides:
      - goos: linux
        format: tar.gz
      - goos: darwin
        format: tar.gz
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'

release:
  github:
    owner: dscv103
    name: fionacode
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

# Homebrew tap - uncomment when homebrew-fifi repository is created
# brews:
#   - name: fifi
#     repository:
#       owner: dscv103
#       name: homebrew-fifi
#       branch: main
#     directory: Formula
#     homepage: https://github.com/dscv103/fionacode
#     description: "FionaCode CLI - Initialize OpenCode AI projects"
#     license: MIT
#     test: |
#       system "#{bin}/fifi version"
#     install: |
#       bin.install "fifi"
